# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
# Trigger the workflow on push request,
  schedule:
    - cron: "0 0 * * *"
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Heroku
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          pip3 install -r  ${{ github.workspace }}/requirements.txt
          python3 ${{ github.workspace }}/src/scripts/detect_pkn_data.py
      - name: Push changes to server
        run: |
          git push heroku main
      - run: echo "🍏 This job's status is ${{ job.status }}."